language: python
python:
- '3.8'
install:
- pip install -r ./config/install_requires.txt
script: python -m unittest
deploy:
  provider: pypi
  user: __token__
  on:
    branch: release
  password:
    secure: BmV5TwIcvm5k5RreSqlRDNNLO776VTiFt9KlWiiBaG00MrAcaKCt/ba832e60fyGO1XhcnF0m9D9JmzgZiXQpxhIQVRF5H3SOL6r3LuLqn7m1y5ms3SUAMJi9sbU9u1fZ8EXTPivxHVDjsnfrVD8rR7oaKCp6fFocFZ80HuQ2Hr/VrpHQp/7DRbiFimrXbbYKupTsJARLMDFJuSEVYLHTeC6NnJSuvqpXjwTtcTvDfHaJyaPZzauv6ewTPaBvITdvYRJjVoxflHS7fIrMSLbPIqyX+D0RNHTAGlBcppdYsX7txNsXvXI4Um2/ewueNVp4fveeKBCC4xt0brWwkZtrV6VD0McS/Tw1+ZQd+Yd5fERtYwo9nKeD60VzPkavV0P5SQkQN3BFADmHEG/mTg9BoSgwddI9PSwcUAZuKkJMHw9Vfijrw6j3BVJAIuenpNDf92TMc+h2ulipTNEn2/a0gpWoA8G7E28+Z4OMbLHVNfM7VuhWxm9z0wxuAI8qrdqAWgzDQcBFp+W1SlQsrsvAqo2/8/6bcKVswr/OIzIJVbxiEhNHrb3HkiO4VZVlOxo7/bO3929BGlpX9XcxU8YccmJOuJHdQL1XioGVrkMU4/Pvj1Wt6XePdfpgCQSq6djuxmTgJoWds0Y2SoTw2cPSq8VxODiJ3iR5ksUGxtt0BA=
